// patch_localStorage.js
// 在瀏覽器 F12 → Console 頁籤貼上此腳本後按 Enter
// 將新增的電子掃描紀錄合併入文件庫，不清除現有資料
(function () {
  const KEY = 'audit_documents';
  const newDocs = [
  {
    "id": "REC-01-001",
    "name": "潔沛文件制定修訂廢止申請單20250625",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-06-25",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件制定修訂廢止申請單20250625.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-002",
    "name": "潔沛文件制定修訂廢止申請單20251001 2",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-10-01",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件制定修訂廢止申請單20251001 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-003",
    "name": "潔沛文件制定修訂廢止申請單20251001 3",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-10-01",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件制定修訂廢止申請單20251001 3.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-004",
    "name": "潔沛文件制定修訂廢止申請單20251001 4",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-10-01",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件制定修訂廢止申請單20251001 4.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-005",
    "name": "潔沛文件制定修訂廢止申請單20251001",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-10-01",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件制定修訂廢止申請單20251001.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-006",
    "name": "潔沛文件制定修訂廢止申請單20251201",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-01",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件制定修訂廢止申請單20251201.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-007",
    "name": "潔沛文件管制總攬表工作指導書2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件管制總攬表工作指導書2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-008",
    "name": "潔沛文件管制總攬表程序文件品質手冊2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件管制總攬表程序文件品質手冊2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-009",
    "name": "潔沛文件管制總攬表程序文件系統程序2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件管制總攬表程序文件系統程序2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-010",
    "name": "潔沛文件管理總攬表2025 1",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件管理總攬表2025 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-011",
    "name": "潔沛文件管理總攬表2025 2",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛文件管理總攬表2025 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-01-012",
    "name": "潔沛知識管理清單2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/1 文件化資訊管制程序/記錄/潔沛知識管理清單2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-02-001",
    "name": "品質目標管制表2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/2 組織環境與績效管理程序/記錄/品質目標管制表2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-02-002",
    "name": "組織風險評估及應對行動表2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/2 組織環境與績效管理程序/記錄/組織風險評估及應對行動表2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-001",
    "name": "潔沛教育訓練申請單2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練申請單2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-002",
    "name": "潔沛教育訓練紀錄表1",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練紀錄表1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-003",
    "name": "潔沛教育訓練紀錄表2",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練紀錄表2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-004",
    "name": "潔沛教育訓練紀錄表3",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練紀錄表3.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-005",
    "name": "潔沛教育訓練紀錄表4",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練紀錄表4.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-006",
    "name": "潔沛教育訓練紀錄表5",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練紀錄表5.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-007",
    "name": "潔沛教育訓練紀錄表6",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練紀錄表6.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-008",
    "name": "潔沛教育訓練紀錄表7",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練紀錄表7.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-009",
    "name": "潔沛教育訓練紀錄表8",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練紀錄表8.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-010",
    "name": "潔沛教育訓練紀錄表9",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/潔沛教育訓練紀錄表9.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-011",
    "name": "114年潔沛教育訓練統計表",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2026-01-20",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/114年潔沛教育訓練統計表.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-012",
    "name": "潔沛參訓人員簽到表20250526",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-05-26",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/潔沛參訓人員簽到表20250526.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-013",
    "name": "潔沛參訓人員簽到表20250623",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-06-23",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/潔沛參訓人員簽到表20250623.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-014",
    "name": "潔沛參訓人員簽到表20250630",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-06-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/潔沛參訓人員簽到表20250630.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-015",
    "name": "潔沛參訓人員簽到表20251001",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-10-01",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/潔沛參訓人員簽到表20251001.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-016",
    "name": "潔沛參訓人員簽到表20251003",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-10-03",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/潔沛參訓人員簽到表20251003.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-017",
    "name": "潔沛參訓人員簽到表20251008",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-10-08",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/潔沛參訓人員簽到表20251008.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-018",
    "name": "潔沛參訓人員簽到表20251104",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-11-04",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/潔沛參訓人員簽到表20251104.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-019",
    "name": "潔沛參訓人員簽到表20251105",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-11-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/潔沛參訓人員簽到表20251105.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-03-020",
    "name": "潔沛教育訓練計劃表2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/3 人力資源及訓練管理程序/記錄/114年度教育訓練/潔沛教育訓練計劃表2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-001",
    "name": "TTV每日保養點檢表-20251222Copy",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-22",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/TTV每日保養點檢表-20251222Copy.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-002",
    "name": "潔沛機器設備一覽表2025",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛機器設備一覽表2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-003",
    "name": "潔沛設備日常保養檢查表(AOI)202511",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(AOI)202511.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-004",
    "name": "潔沛設備日常保養檢查表(AOI)202512",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(AOI)202512.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-005",
    "name": "潔沛設備日常保養檢查表(OCR)202511",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(OCR)202511.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-006",
    "name": "潔沛設備日常保養檢查表(OCR)202512",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(OCR)202512.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-007",
    "name": "潔沛設備日常保養檢查表(TTV)202511",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(TTV)202511.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-008",
    "name": "潔沛設備日常保養檢查表(TTV)202512",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(TTV)202512.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-009",
    "name": "潔沛設備日常保養檢查表(清洗機)202511",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(清洗機)202511.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-010",
    "name": "潔沛設備日常保養檢查表(清洗機)202512",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(清洗機)202512.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-011",
    "name": "潔沛設備日常保養檢查表(超音波)202511",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(超音波)202511.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-012",
    "name": "潔沛設備日常保養檢查表(超音波)202512",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備日常保養檢查表(超音波)202512.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-013",
    "name": "潔沛設備驗收單(AOI) 1",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(AOI) 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-014",
    "name": "潔沛設備驗收單(AOI) 2",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(AOI) 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-015",
    "name": "潔沛設備驗收單(NAS) 1",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(NAS) 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-016",
    "name": "潔沛設備驗收單(NAS) 2",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(NAS) 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-017",
    "name": "潔沛設備驗收單(OCR) 1",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(OCR) 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-018",
    "name": "潔沛設備驗收單(OCR) 2",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(OCR) 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-019",
    "name": "潔沛設備驗收單(TTV) 1",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(TTV) 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-020",
    "name": "潔沛設備驗收單(TTV) 2",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(TTV) 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-021",
    "name": "潔沛設備驗收單(終端清洗機) 1",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(終端清洗機) 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-022",
    "name": "潔沛設備驗收單(終端清洗機) 2",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(終端清洗機) 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-023",
    "name": "潔沛設備驗收單(超音波) 1",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(超音波) 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-024",
    "name": "潔沛設備驗收單(超音波) 2",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(超音波) 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-025",
    "name": "潔沛設備驗收單(超音波)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設備驗收單(超音波).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-026",
    "name": "潔沛設設設備年度保養計劃表2025",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2025-12-19",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/潔沛設設設備年度保養計劃表2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-027",
    "name": "設施設備管理程序2.0",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/設施設備管理程序2.0.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-028",
    "name": "4.2 設備驗收單",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/表單/4.2 設備驗收單.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-029",
    "name": "4.4 設備維護履歷卡",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/表單/4.4 設備維護履歷卡.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-030",
    "name": "4.2.1設備驗收單(超音波)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/4.2.1設備驗收單(超音波).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-031",
    "name": "4.4.1潔沛設備維護履歷卡(超音波清洗機)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/4.4.1潔沛設備維護履歷卡(超音波清洗機).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-032",
    "name": "4.4.2潔沛設備維護履歷卡(終端清洗機)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/4.4.2潔沛設備維護履歷卡(終端清洗機).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-033",
    "name": "4.4.3潔沛設備維護履歷卡(OCR篩選機)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/4.4.3潔沛設備維護履歷卡(OCR篩選機).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-034",
    "name": "4.4.4潔沛設備維護履歷卡(AOI)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/4.4.4潔沛設備維護履歷卡(AOI).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-035",
    "name": "4.4.5潔沛設備維護履歷卡(TTV)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/4.4.5潔沛設備維護履歷卡(TTV).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-036",
    "name": "4.4.6潔沛設備維護履歷卡(NAS)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/4.4.6潔沛設備維護履歷卡(NAS).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-037",
    "name": "4.3.1潔沛設備保養紀錄表(超音波清洗機)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/設備保養紀錄表114年度/4.3.1潔沛設備保養紀錄表(超音波清洗機).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-038",
    "name": "4.4.2潔沛設備維護履歷卡(清洗機)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/設備保養紀錄表114年度/4.4.2潔沛設備維護履歷卡(清洗機).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-04-039",
    "name": "潔沛設備維護履歷卡(空壓機) (2)",
    "type": "記錄",
    "version": "",
    "department": "工程部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/4 設施設備管理程序/記錄/設備保養紀錄表114年度/潔沛設備維護履歷卡(空壓機) (2).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-001",
    "name": "潔沛手持式微粒子計數器校正報告1",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/潔沛手持式微粒子計數器校正報告1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-002",
    "name": "潔沛手持式微粒子計數器校正報告2",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/潔沛手持式微粒子計數器校正報告2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-003",
    "name": "潔沛量測儀器年校正計劃表2025",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-18",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/潔沛量測儀器年校正計劃表2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-004",
    "name": "潔沛量規儀器一覽表2025",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/潔沛量規儀器一覽表2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-005",
    "name": "潔沛量規儀器履歷表(AOI)",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/潔沛量規儀器履歷表(AOI).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-006",
    "name": "潔沛量規儀器履歷表(WAFER厚度量測系統)",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/潔沛量規儀器履歷表(WAFER厚度量測系統).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-007",
    "name": "潔沛量規儀器履歷表(手持式微粒子計數器I)",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/潔沛量規儀器履歷表(手持式微粒子計數器I).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-008",
    "name": "量測資源管理程序2.0",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/量測資源管理程序2.0.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-009",
    "name": "5.1量規儀器一覽表",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/表單/5.1量規儀器一覽表.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-05-010",
    "name": "9.1量規儀器一覽表",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/5 量測資源管理程序/記錄/9.1量規儀器一覽表.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-06-001",
    "name": "工作環境管理程序(20251009要重印有改)",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-10-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/6 工作環境管理程序/工作環境管理程序(20251009要重印有改).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-06-002",
    "name": "工作環境管理程序(舊版不要用)",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/6 工作環境管理程序/工作環境管理程序(舊版不要用).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-06-003",
    "name": "潔沛環境監控記錄表202511",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/6 工作環境管理程序/潔沛環境監控記錄表202511.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-06-004",
    "name": "潔沛環境監控記錄表202512",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-31",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/6 工作環境管理程序/潔沛環境監控記錄表202512.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-07-001",
    "name": "資訊管理程序2.0",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/7 資訊管理程序/資訊管理程序2.0.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-001",
    "name": "客戶服務管理程序(1.0)",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/客戶服務管理程序(1.0).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-002",
    "name": "客戶服務管理程序(2.0)",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/客戶服務管理程序(2.0).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-003",
    "name": "潔沛供應商評鑑管理表2025 1",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛供應商評鑑管理表2025 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-004",
    "name": "潔沛供應商評鑑管理表2025 2",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛供應商評鑑管理表2025 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-005",
    "name": "潔沛供應商評鑑管理表2025 3",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛供應商評鑑管理表2025 3.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-006",
    "name": "潔沛供應商評鑑管理表2025 4",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛供應商評鑑管理表2025 4.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-007",
    "name": "潔沛供應商評鑑管理表2025 5",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛供應商評鑑管理表2025 5.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-008",
    "name": "潔沛供應商評鑑管理表2025 6",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛供應商評鑑管理表2025 6.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-009",
    "name": "潔沛年度供應商評鑑表2025",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛年度供應商評鑑表2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-010",
    "name": "潔沛新產品試做評估單20250911",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-11",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產品試做評估單20250911.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-011",
    "name": "潔沛新產品試做評估單20250918",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-18",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產品試做評估單20250918.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-012",
    "name": "潔沛新產品試做評估單20250924",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-24",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產品試做評估單20250924.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-013",
    "name": "潔沛新產品試做評估單20251001",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-01",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產品試做評估單20251001.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-014",
    "name": "潔沛新產品試做評估單20251008",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-08",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產品試做評估單20251008.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-015",
    "name": "潔沛新產品試做評估單20251016",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產品試做評估單20251016.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-016",
    "name": "潔沛新產品試做評估單20251022",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-22",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產品試做評估單20251022.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-017",
    "name": "潔沛新產測試評估單C002-1",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產測試評估單C002-1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-018",
    "name": "潔沛新產測試評估單C002-2",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產測試評估單C002-2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-019",
    "name": "潔沛新產測試評估單C002-3",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產測試評估單C002-3.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-020",
    "name": "潔沛新產測試評估單C002-4",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產測試評估單C002-4.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-021",
    "name": "潔沛新產測試評估單C002-5",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛新產測試評估單C002-5.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-022",
    "name": "潔沛日常紀錄既稽核表單",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-29",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛日常紀錄既稽核表單.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-023",
    "name": "潔沛樣品測試承認表20250905",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛樣品測試承認表20250905.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-024",
    "name": "潔沛樣品測試承認表20250915",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-15",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛樣品測試承認表20250915.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-025",
    "name": "潔沛樣品測試承認表20250919",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-19",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛樣品測試承認表20250919.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-026",
    "name": "潔沛樣品測試承認表20250926",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-26",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛樣品測試承認表20250926.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-027",
    "name": "潔沛樣品測試承認表20251003",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-03",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛樣品測試承認表20251003.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-028",
    "name": "潔沛樣品測試承認表20251013",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-13",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛樣品測試承認表20251013.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-029",
    "name": "潔沛樣品測試承認表20251017",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-17",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛樣品測試承認表20251017.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-030",
    "name": "潔沛藥水測試紀錄表20250905",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表20250905.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-031",
    "name": "潔沛藥水測試紀錄表20250915",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-15",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表20250915.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-032",
    "name": "潔沛藥水測試紀錄表20250919",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-19",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表20250919.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-033",
    "name": "潔沛藥水測試紀錄表20250926",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-09-26",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表20250926.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-034",
    "name": "潔沛藥水測試紀錄表20251003",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-03",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表20251003.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-035",
    "name": "潔沛藥水測試紀錄表20251013",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-13",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表20251013.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-036",
    "name": "潔沛藥水測試紀錄表20251017",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-10-17",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表20251017.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-037",
    "name": "潔沛藥水測試紀錄表20251127",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-11-27",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表20251127.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-038",
    "name": "潔沛藥水測試紀錄表20251205",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表20251205.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-039",
    "name": "潔沛藥水測試紀錄表C002-1",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表C002-1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-040",
    "name": "潔沛藥水測試紀錄表C002-2",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表C002-2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-041",
    "name": "潔沛藥水測試紀錄表C002-3",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表C002-3.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-042",
    "name": "潔沛藥水測試紀錄表C002-4",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表C002-4.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-043",
    "name": "潔沛藥水測試紀錄表C002-5",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2025-12-30",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/潔沛藥水測試紀錄表C002-5.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-044",
    "name": "8.2客戶抱怨單",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/表單/8.2客戶抱怨單.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-045",
    "name": "8.3客戶滿意度調查表",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/表單/8.3客戶滿意度調查表.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-08-046",
    "name": "9.3樣品測試承認表(隆達電子)",
    "type": "記錄",
    "version": "",
    "department": "業務部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/8 客戶服務管理程序/記錄/隆達電子/9.3樣品測試承認表(隆達電子).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-001",
    "name": "潔沛內部稽核報告書2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/潔沛內部稽核報告書2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-002",
    "name": "潔沛內部稽核查檢表2025 1",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/潔沛內部稽核查檢表2025 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-003",
    "name": "潔沛內部稽核查檢表2025 2",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/潔沛內部稽核查檢表2025 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-004",
    "name": "潔沛內部稽核查檢表2025 3",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/潔沛內部稽核查檢表2025 3.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-005",
    "name": "潔沛內部稽核查檢表2025 4",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/潔沛內部稽核查檢表2025 4.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-006",
    "name": "潔沛內部稽核查檢表2025 5",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/潔沛內部稽核查檢表2025 5.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-007",
    "name": "潔沛內部稽核計劃表2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/潔沛內部稽核計劃表2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-008",
    "name": "潔沛合格內部稽核人員名冊2025",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/潔沛合格內部稽核人員名冊2025.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-009",
    "name": "9.1 內部稽核計畫表",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/表單/9.1 內部稽核計畫表.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-010",
    "name": "9.2 合格內部稽核人員名冊",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/表單/9.2 合格內部稽核人員名冊.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-011",
    "name": "9.4 內部稽核矯正通知單",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/表單/9.4 內部稽核矯正通知單.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-09-012",
    "name": "9.4內部稽核矯正通知單",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/9 內部稽核管理程序/記錄/內部稽核114年度/9.4內部稽核矯正通知單.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-001",
    "name": "採購及供應商管理程序(2.0)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/採購及供應商管理程序(2.0).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-002",
    "name": "採購及供應商管理程序(新版)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/採購及供應商管理程序(新版).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-003",
    "name": "潔沛客戶訂購單20251106",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-11-06",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/潔沛客戶訂購單20251106.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-004",
    "name": "潔沛客戶訂購單20260105",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-01-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/潔沛客戶訂購單20260105.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-005",
    "name": "潔沛訂購單20250716",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-07-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/潔沛訂購單20250716.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-006",
    "name": "潔沛訂購單20250902",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-09-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/潔沛訂購單20250902.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-007",
    "name": "潔沛訂購單20251106",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-11-06",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/潔沛訂購單20251106.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-008",
    "name": "潔沛訂購單20251219",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-12-19",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/潔沛訂購單20251219.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-009",
    "name": "潔沛訂購單20251224",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-12-24",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/潔沛訂購單20251224.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-010",
    "name": "潔沛訂購單20260102",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/潔沛訂購單20260102.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-011",
    "name": "潔沛訂購單20260116",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-01-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/潔沛訂購單20260116.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-012",
    "name": "10.1耗材設備訂購單",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/表單/10.1耗材設備訂購單.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-013",
    "name": "10.1耗材設備訂購單(07月16日)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/10.1耗材設備訂購單(07月16日).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-014",
    "name": "10.1耗材設備訂購單(11月6日)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/10.1耗材設備訂購單(11月6日).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-015",
    "name": "10.1耗材設備訂購單(9月2日)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/10.1耗材設備訂購單(9月2日).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-016",
    "name": "10.3供應商定期評鑑表-1(楊特)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/10.3供應商定期評鑑表-1(楊特).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-017",
    "name": "10.3供應商定期評鑑表-4(鏵友益)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/10.3供應商定期評鑑表-4(鏵友益).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-018",
    "name": "10.3供應商定期評鑑表-5(奈米趨勢)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/10.3供應商定期評鑑表-5(奈米趨勢).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-019",
    "name": "10.3供應商定期評鑑表-6(拓生科技)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/10.3供應商定期評鑑表-6(拓生科技).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-020",
    "name": "10.3供應商評鑑管理表-2(金華瑋)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/10.3供應商評鑑管理表-2(金華瑋).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-021",
    "name": "10.3供應商評鑑管理表-3(2025柏連)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/10.3供應商評鑑管理表-3(2025柏連).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-10-022",
    "name": "供應商評鑑表(2025)(廢除)",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/10 採購及供應商管理程序/記錄/供應商評鑑表(2025)(廢除).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-001",
    "name": "潔沛企業領料單20260108",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-08",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛企業領料單20260108.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-002",
    "name": "潔沛生產日報目檢表20260105",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報目檢表20260105.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-003",
    "name": "潔沛生產日報目檢表20260106",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-06",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報目檢表20260106.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-004",
    "name": "潔沛生產日報目檢表20260107",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-07",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報目檢表20260107.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-005",
    "name": "潔沛生產日報目檢表20260108",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-08",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報目檢表20260108.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-006",
    "name": "潔沛生產日報目檢表20260109",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報目檢表20260109.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-007",
    "name": "潔沛生產日報目檢表20260110",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報目檢表20260110.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-008",
    "name": "潔沛生產日報表20251110",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報表20251110.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-009",
    "name": "潔沛生產日報表20251112",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-12",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報表20251112.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-010",
    "name": "潔沛生產日報表20251113",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-13",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報表20251113.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-011",
    "name": "潔沛生產日報表20251210",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報表20251210.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-012",
    "name": "潔沛生產日報表20251217",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-17",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報表20251217.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-013",
    "name": "潔沛生產日報表20251218",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-18",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報表20251218.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-014",
    "name": "潔沛生產日報表20251219",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-19",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產日報表20251219.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-015",
    "name": "潔沛生產計劃表20251110",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產計劃表20251110.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-016",
    "name": "潔沛生產計劃表20251127",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-27",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產計劃表20251127.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-017",
    "name": "潔沛生產計劃表20251210",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產計劃表20251210.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-018",
    "name": "潔沛生產計劃表20251217",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-17",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產計劃表20251217.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-019",
    "name": "潔沛生產計劃表20260105",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產計劃表20260105.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-020",
    "name": "潔沛生產計劃表20260121",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-21",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛生產計劃表20260121.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-021",
    "name": "潔沛領料單20250908",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-09-08",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20250908.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-022",
    "name": "潔沛領料單20251110 1",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251110 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-023",
    "name": "潔沛領料單20251110 2",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251110 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-024",
    "name": "潔沛領料單20251112 1",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-12",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251112 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-025",
    "name": "潔沛領料單20251112 2",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-12",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251112 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-026",
    "name": "潔沛領料單20251113",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-11-13",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251113.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-027",
    "name": "潔沛領料單20251210",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251210.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-028",
    "name": "潔沛領料單20251217",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-17",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251217.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-029",
    "name": "潔沛領料單20251219",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-19",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251219.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-030",
    "name": "潔沛領料單20251222",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-22",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251222.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-031",
    "name": "潔沛領料單20251223",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2025-12-23",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20251223.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-032",
    "name": "潔沛領料單202601051",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單202601051.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-033",
    "name": "潔沛領料單202601052",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單202601052.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-034",
    "name": "潔沛領料單20260106",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-06",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20260106.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-035",
    "name": "潔沛領料單20260107",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-07",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20260107.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-036",
    "name": "潔沛領料單20260108",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-08",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20260108.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-037",
    "name": "潔沛領料單20260121",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-21",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20260121.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-038",
    "name": "潔沛領料單2026012201",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-22",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單2026012201.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-039",
    "name": "潔沛領料單2026012202",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-22",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單2026012202.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-040",
    "name": "潔沛領料單2026012203",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-22",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單2026012203.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-041",
    "name": "潔沛領料單2026012301",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-23",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單2026012301.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-042",
    "name": "潔沛領料單2026012302",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-23",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單2026012302.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-043",
    "name": "潔沛領料單2026012601",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-26",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單2026012601.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-044",
    "name": "潔沛領料單2026012602",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-26",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單2026012602.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-045",
    "name": "潔沛領料單20260127",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-27",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20260127.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-046",
    "name": "潔沛領料單20260128",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-01-28",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/潔沛領料單20260128.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-11-047",
    "name": "生產作業管理程序(2.0)",
    "type": "記錄",
    "version": "",
    "department": "生產課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/11 生產作業管理程序/生產作業管理程序(2.0).pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-001",
    "name": "BL3798承認書",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/BL3798承認書.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-002",
    "name": "BL900承認書",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-15",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/BL900承認書.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-003",
    "name": "品質管理紀錄表20260102",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2026-01-02",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/品質管理紀錄表20260102.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-004",
    "name": "潔沛品質管理紀錄表20250905 1",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-09-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20250905 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-005",
    "name": "潔沛品質管理紀錄表20250905 2",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-09-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20250905 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-006",
    "name": "潔沛品質管理紀錄表20250915",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-09-15",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20250915.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-007",
    "name": "潔沛品質管理紀錄表20250919",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-09-19",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20250919.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-008",
    "name": "潔沛品質管理紀錄表20250926",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-09-26",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20250926.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-009",
    "name": "潔沛品質管理紀錄表20251003",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-10-03",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20251003.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-010",
    "name": "潔沛品質管理紀錄表20251013",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-10-13",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20251013.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-011",
    "name": "潔沛品質管理紀錄表20251107 1",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-11-07",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20251107 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-012",
    "name": "潔沛品質管理紀錄表20251107 2",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-11-07",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20251107 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-013",
    "name": "潔沛品質管理紀錄表20251110 1",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-11-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20251110 1.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-014",
    "name": "潔沛品質管理紀錄表20251110 2",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-11-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20251110 2.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-015",
    "name": "潔沛品質管理紀錄表20251110",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-11-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20251110.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-016",
    "name": "潔沛品質管理紀錄表20251112",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-11-12",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20251112.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-017",
    "name": "潔沛品質管理紀錄表20251113",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-11-13",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛品質管理紀錄表20251113.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-12-018",
    "name": "潔沛材料測試承認表20250905",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-09-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/12 品質檢驗管理程序/潔沛材料測試承認表20250905.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-13-001",
    "name": "13.1特採申請單",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2026-03-09",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/13 不合格品管制程序/表單/13.1特採申請單.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-001",
    "name": "潔沛企業出貨檢查紀錄表20260112",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-01-12",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛企業出貨檢查紀錄表20260112.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-002",
    "name": "潔沛入庫單20251112",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-11-12",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛入庫單20251112.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-003",
    "name": "潔沛入庫單2025111301",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-11-13",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛入庫單2025111301.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-004",
    "name": "潔沛入庫單2025111302",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-11-13",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛入庫單2025111302.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-005",
    "name": "潔沛入庫單20251127",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-11-27",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛入庫單20251127.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-006",
    "name": "潔沛入庫單20251210",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-12-10",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛入庫單20251210.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-007",
    "name": "潔沛入庫單20251217",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-12-17",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛入庫單20251217.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-008",
    "name": "潔沛入庫單20260105",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-01-05",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛入庫單20260105.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-009",
    "name": "潔沛入庫單20260106",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-01-06",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛入庫單20260106.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-010",
    "name": "潔沛入庫單20260107",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-01-07",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛入庫單20260107.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-011",
    "name": "潔沛出貨單20251114",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2025-11-14",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛出貨單20251114.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-14-012",
    "name": "潔沛出貨單20260112",
    "type": "記錄",
    "version": "",
    "department": "資材課",
    "createdDate": "2026-01-12",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/14 倉儲管理程序/潔沛出貨單20260112.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-15-001",
    "name": "潔沛不符合及矯正措施報告表",
    "type": "記錄",
    "version": "",
    "department": "品保課",
    "createdDate": "2025-12-16",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/15 不符合及矯正措施管理程序/潔沛不符合及矯正措施報告表.pdf",
    "docxPath": ""
  },
  {
    "id": "REC-16-001",
    "name": "管理審查會議20250912",
    "type": "記錄",
    "version": "",
    "department": "管理部",
    "createdDate": "2025-09-12",
    "author": "",
    "retentionYears": 10,
    "pdfPath": "../NAS/公用/ISO文件建立/潔沛修訂版/電子掃描紀錄/16 管理審查程序/管理審查會議20250912.pdf",
    "docxPath": ""
  }
];

  let existing = [];
  try { existing = JSON.parse(localStorage.getItem(KEY) || '[]'); } catch (e) {}

  const existingNames = new Set(existing.map(d => d.name));
  const existingPaths = new Set(existing.map(d => d.pdfPath).filter(Boolean));

  let added = 0, skipped = 0;
  for (const doc of newDocs) {
    if (existingNames.has(doc.name) || (doc.pdfPath && existingPaths.has(doc.pdfPath))) {
      skipped++;
      continue;
    }
    existing.push(doc);
    existingNames.add(doc.name);
    if (doc.pdfPath) existingPaths.add(doc.pdfPath);
    added++;
  }

  localStorage.setItem(KEY, JSON.stringify(existing));
  console.log(`[OK] 完成：新增 ${added} 筆，跳過（重複）${skipped} 筆`);
  console.log(`文件庫現有 ${existing.length} 筆文件`);
})();
