with open(r'C:\Users\USER\Desktop\自動稽核程式\audit-dashboard.jsx', 'r', encoding='utf-8-sig') as f:
    lines = f.readlines()

print(f"Total lines: {len(lines)}")

# Lines 274-325 (0-indexed: 273-324) are the DocumentsTab function body to replace
# We'll replace lines 274..325 (1-indexed) = index 273..324 inclusive
START = 273   # 0-indexed, inclusive
END   = 324   # 0-indexed, inclusive

new_block = [
'function DocumentsTab({ documents, setDocuments }) {\n',
'  const [modal, setModal] = useState(null);\n',
'  const [showAdd, setShowAdd] = useState(false);\n',
'  const [err, setErr] = useState("");\n',
'  const emptyDoc = { id: "", name: "", type: "\u7ba1\u7406\u7a0b\u5e8f", version: "1.0", department: "", createdDate: "", author: "", retentionYears: 16, fileName: "", fileSize: "", fileType: "", fileData: "" };\n',
'  const [newDoc, setNewDoc] = useState({ ...emptyDoc });\n',
'  const enriched = documents.map(d => {\n',
'    const expiryDate = new Date(d.createdDate);\n',
'    expiryDate.setFullYear(expiryDate.getFullYear() + (d.retentionYears || 16));\n',
'    const expiryStr = expiryDate.toISOString().split("T")[0];\n',
'    const daysToExpiry = daysUntil(expiryStr);\n',
'    return { ...d, expiryStr, daysToExpiry };\n',
'  });\n',
'  function parseDocxMeta(ab) {\n',
'    try {\n',
'      const raw = new TextDecoder("utf-8", { fatal: false }).decode(new Uint8Array(ab));\n',
'      const g = (re) => (raw.match(re)||[])[1]||"";\n',
'      const title    = g(/<dc:title[^>]*>([^<]*)<\\/dc:title>/);\n',
'      const creator  = g(/<dc:creator[^>]*>([^<]*)<\\/dc:creator>/) || g(/<cp:lastModifiedBy[^>]*>([^<]*)<\\/cp:lastModifiedBy>/);\n',
'      const revision = g(/<cp:revision[^>]*>([^<]*)<\\/cp:revision>/);\n',
'      const created  = g(/<dcterms:created[^>]*>([^<]*)<\\/dcterms:created>/);\n',
'      const modified = g(/<dcterms:modified[^>]*>([^<]*)<\\/dcterms:modified>/);\n',
'      return { title, creator, revision, created, modified };\n',
'    } catch(e) { return {}; }\n',
'  }\n',
'  function parsePdfMeta(ab) {\n',
'    try {\n',
'      const raw = new TextDecoder("latin1", { fatal: false }).decode(new Uint8Array(ab));\n',
'      const g = (re) => (raw.match(re)||[])[1]||"";\n',
'      const title  = g(/\\/Title\\s*\\(([^)]+)\\)/);\n',
'      const author = g(/\\/Author\\s*\\(([^)]+)\\)/);\n',
'      const d      = g(/\\/CreationDate\\s*\\(D:(\\d{8})/);\n',
'      return { title, author, date: d.length===8 ? `${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}` : "" };\n',
'    } catch(e) { return {}; }\n',
'  }\n',
'  function handleFileUpload(e) {\n',
'    const file = e.target.files[0]; if (!file) return;\n',
'    const ext = file.name.split(".").pop().toLowerCase();\n',
'    const sizeStr = file.size > 1048576 ? (file.size/1048576).toFixed(1)+" MB" : (file.size/1024).toFixed(0)+" KB";\n',
'    setNewDoc(prev => ({ ...prev, fileName: file.name, fileSize: sizeStr, fileType: ext.toUpperCase(), name: prev.name || file.name.replace(/\\.[^.]+$/, "") }));\n',
'    const reader = new FileReader();\n',
'    reader.onload = ev => {\n',
'      const ab = ev.target.result;\n',
'      const b64r = new FileReader();\n',
'      b64r.onload = e2 => setNewDoc(prev => ({ ...prev, fileData: e2.target.result }));\n',
'      b64r.readAsDataURL(file);\n',
'      if (["docx","xlsx","pptx"].includes(ext)) {\n',
'        const m = parseDocxMeta(ab);\n',
'        setNewDoc(prev => ({\n',
'          ...prev,\n',
'          name:        m.title    || prev.name,\n',
'          author:      m.creator  || prev.author,\n',
'          version:     m.revision ? (parseInt(m.revision)>0 ? `1.${parseInt(m.revision)-1}` : "1.0") : prev.version,\n',
'          createdDate: (m.created||m.modified||"").substring(0,10) || prev.createdDate,\n',
'        }));\n',
'      } else if (ext === "pdf") {\n',
'        const m = parsePdfMeta(ab);\n',
'        setNewDoc(prev => ({ ...prev, name: m.title||prev.name, author: m.author||prev.author, createdDate: m.date||prev.createdDate }));\n',
'      }\n',
'    };\n',
'    reader.readAsArrayBuffer(file);\n',
'  }\n',
'  function handleAdd() {\n',
'    if (!newDoc.id.trim()||!newDoc.name.trim()||!newDoc.department.trim()||!newDoc.createdDate) {\n',
'      setErr("\u8acb\u586b\u5beb\u6240\u6709\u5fc5\u586b\u6b04\u4f4d\uff1a\u6587\u4ef6\u7de8\u865f\u3001\u540d\u7a31\u3001\u5236\u5b9a\u90e8\u9580\u3001\u5236\u5b9a\u65e5\u671f"); return;\n',
'    }\n',
'    setErr("");\n',
'    setDocuments(prev => [...prev, { ...newDoc, retentionYears: parseInt(newDoc.retentionYears)||16 }]);\n',
'    setShowAdd(false);\n',
'    setNewDoc({ ...emptyDoc });\n',
'  }\n',
'  return (\n',
'    <div>\n',
'      <SectionHeader title="\u6587\u4ef6\u7248\u672c\u7ba1\u63a7" count={documents.length} color="#a78bfa" />\n',
'      <div style={{ display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" }}>\n',
'        <StatCard label="\u7ba1\u7406\u624b\u518a" value={documents.filter(d => d.type === "\u7ba1\u7406\u624b\u518a").length} color="#a78bfa" />\n',
'        <StatCard label="\u7ba1\u7406\u7a0b\u5e8f" value={documents.filter(d => d.type === "\u7ba1\u7406\u7a0b\u5e8f").length} color="#60a5fa" />\n',
'        <StatCard label="\u7e3d\u6587\u4ef6\u6578" value={documents.length} color="#34d399" />\n',
'      </div>\n',
'      <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 14 }}>\n',
'        <button onClick={() => setShowAdd(true)} style={{ background: "linear-gradient(135deg, #7c3aed, #4f46e5)", border: "none", borderRadius: 10, color: "#fff", cursor: "pointer", padding: "9px 18px", fontSize: 13, fontWeight: 700 }}>\uff0b \u65b0\u589e\u6587\u4ef6</button>\n',
'      </div>\n',
'      <div style={{ overflowX: "auto" }}>\n',
'        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>\n',
'          <thead><tr>{["\u6587\u4ef6\u7de8\u865f","\u6587\u4ef6\u540d\u7a31","\u985e\u5225","\u7248\u672c","\u5236\u5b9a\u90e8\u9580","\u5236\u5b9a\u65e5\u671f","\u5236\u5b9a\u8005","\u4fdd\u5b58\u81f3","\u6a94\u6848",""].map(h => (<th key={h} style={{ textAlign: "left", padding: "10px 12px", color: "#64748b", fontWeight: 600, borderBottom: "1px solid rgba(255,255,255,0.06)", whiteSpace: "nowrap" }}>{h}</th>))}</tr></thead>\n',
'          <tbody>\n',
'            {enriched.map((doc, i) => (\n',
'              <tr key={doc.id} style={{ background: i % 2 === 0 ? "rgba(255,255,255,0.02)" : "transparent" }}>\n',
'                <td style={{ padding: "10px 12px", color: "#60a5fa", fontWeight: 700, fontFamily: "monospace" }}>{doc.id}</td>\n',
'                <td style={{ padding: "10px 12px", color: "#e2e8f0", fontWeight: 600 }}>{doc.name}</td>\n',
'                <td style={{ padding: "10px 12px" }}><Badge color={doc.type === "\u7ba1\u7406\u624b\u518a" ? "#a78bfa" : "#60a5fa"}>{doc.type}</Badge></td>\n',
'                <td style={{ padding: "10px 12px" }}><span style={{ background: "rgba(34,197,94,0.1)", color: "#4ade80", borderRadius: 6, padding: "2px 8px", fontWeight: 700, fontFamily: "monospace" }}>v{doc.version}</span></td>\n',
'                <td style={{ padding: "10px 12px", color: "#94a3b8" }}>{doc.department}</td>\n',
'                <td style={{ padding: "10px 12px", color: "#94a3b8", whiteSpace: "nowrap" }}>{formatDate(doc.createdDate)}</td>\n',
'                <td style={{ padding: "10px 12px", color: "#94a3b8" }}>{doc.author}</td>\n',
'                <td style={{ padding: "10px 12px", whiteSpace: "nowrap" }}><span style={{ color: doc.daysToExpiry < 365 ? "#f97316" : "#64748b", fontFamily: "monospace", fontSize: 12 }}>{formatDate(doc.expiryStr)}</span></td>\n',
'                <td style={{ padding: "10px 12px" }}>{doc.fileData ? (<a href={doc.fileData} download={doc.fileName||doc.id} style={{ color:"#60a5fa", fontSize:11, textDecoration:"none", background:"rgba(96,165,250,0.1)", borderRadius:6, padding:"3px 8px", border:"1px solid rgba(96,165,250,0.3)" }}>\u2193 {doc.fileType||"\u4e0b\u8f09"}</a>) : <span style={{color:"#374151",fontSize:11}}>\u7121\u6a94\u6848</span>}</td>\n',
'                <td style={{ padding: "10px 12px" }}><button onClick={() => setModal(doc)} style={{ background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 6, color: "#94a3b8", cursor: "pointer", padding: "4px 10px", fontSize: 11 }}>\u8a73\u60c5</button></td>\n',
'              </tr>\n',
'            ))}\n',
'          </tbody>\n',
'        </table>\n',
'      </div>\n',
'      {modal && (\n',
'        <Modal title={`\u6587\u4ef6\u8a73\u60c5\uff1a${modal.id}`} onClose={() => setModal(null)}>\n',
'          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 16 }}>\n',
'            {[["\\u6587\\u4ef6\\u7de8\\u865f", modal.id],["\\u6587\\u4ef6\\u540d\\u7a31", modal.name],["\\u985e\\u5225", modal.type],["\\u7248\\u672c", `v${modal.version}`],["\\u5236\\u5b9a\\u90e8\\u9580", modal.department],["\\u5236\\u5b9a\\u65e5\\u671f", formatDate(modal.createdDate)],["\\u5236\\u5b9a\\u8005", modal.author],["\\u4fdd\\u5b58\\u5e74\\u9650", `${modal.retentionYears} \\u5e74`],["\\u4fdd\\u5b58\\u5230\\u671f\\u65e5", formatDate(modal.expiryStr)],["\\u8ddd\\u5230\\u671f", `${modal.daysToExpiry} \\u5929`]].map(([k,v]) => (<div key={k}><div style={{ fontSize: 11, color: "#64748b", marginBottom: 4 }}>{k}</div><div style={{ color: "#e2e8f0", fontWeight: 600, fontSize: 14 }}>{v}</div></div>))}\n',
'          </div>\n',
'          {modal.fileName && (\n',
'            <div style={{ background:"rgba(96,165,250,0.07)", border:"1px solid rgba(96,165,250,0.2)", borderRadius:10, padding:14, display:"flex", alignItems:"center", justifyContent:"space-between" }}>\n',
'              <div>\n',
'                <div style={{ fontSize:13, color:"#93c5fd", fontWeight:700 }}>{modal.fileName}</div>\n',
'                <div style={{ fontSize:11, color:"#64748b", marginTop:4 }}>{modal.fileType} \u2022 {modal.fileSize}</div>\n',
'              </div>\n',
'              {modal.fileData && <a href={modal.fileData} download={modal.fileName} style={{ background:"linear-gradient(135deg,#7c3aed,#4f46e5)", color:"#fff", padding:"8px 18px", borderRadius:8, fontSize:13, fontWeight:700, textDecoration:"none" }}>\u2193 \u4e0b\u8f09\u6a94\u6848</a>}\n',
'            </div>\n',
'          )}\n',
'        </Modal>\n',
'      )}\n',
'      {showAdd && (\n',
'        <Modal title="\u65b0\u589e\u6587\u4ef6" onClose={() => { setShowAdd(false); setErr(""); setNewDoc({...emptyDoc}); }}>\n',
'          <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>\n',
'            {/* File Upload Zone */}\n',
'            <div>\n',
'              <div style={{ fontSize:12, color:"#64748b", marginBottom:6, fontWeight:600 }}>\u4e0a\u50b3\u6587\u4ef6\uff08\u53ef\u81ea\u52d5\u8b80\u53d6 Word / PDF \u5167\u5bb9\u4fe1\u606f\uff09</div>\n',
'              <label style={{ display:"flex", alignItems:"center", gap:12, background:"rgba(255,255,255,0.03)", border:"2px dashed rgba(124,58,237,0.4)", borderRadius:12, padding:"14px 18px", cursor:"pointer", transition:"all 0.2s" }}\n',
'                onMouseEnter={e=>e.currentTarget.style.borderColor="rgba(124,58,237,0.8)"}\n',
'                onMouseLeave={e=>e.currentTarget.style.borderColor="rgba(124,58,237,0.4)"}>\n',
'                <input type="file" accept=".pdf,.docx,.xlsx,.pptx,.doc,.xls,.ppt,.txt" onChange={handleFileUpload} style={{ display:"none" }} />\n',
'                <span style={{ fontSize:28 }}>&#128196;</span>\n',
'                <div>\n',
'                  {newDoc.fileName\n',
'                    ? <><div style={{ color:"#a78bfa", fontWeight:700, fontSize:14 }}>{newDoc.fileName}</div><div style={{ color:"#64748b", fontSize:12 }}>{newDoc.fileType} \u2022 {newDoc.fileSize}</div></>\n',
'                    : <><div style={{ color:"#94a3b8", fontWeight:600 }}>\u9ede\u64ca\u9078\u64c7\u6a94\u6848</div><div style={{ color:"#475569", fontSize:12, marginTop:3 }}>PDF\u3001DOCX\u3001XLSX\u3001PPTX\u2026\uff08\u652f\u63f4\u81ea\u52d5\u8b80\u53d6 Metadata\uff09</div></>\n',
'                  }\n',
'                </div>\n',
'              </label>\n',
'            </div>\n',
'            {/* Required fields */}\n',
'            <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 }}>\n',
'              {[["\\u6587\\u4ef6\\u7de8\\u865f *","id","text"],["\\u7248\\u672c *","version","text"],["\\u5236\\u5b9a\\u90e8\\u9580 *","department","text"],["\\u5236\\u5b9a\\u8005","author","text"]].map(([label,field,type]) => (\n',
'                <div key={field}>\n',
'                  <div style={{ fontSize:12, color:"#64748b", marginBottom:5 }}>{label}</div>\n',
'                  <input type={type} value={newDoc[field]} onChange={e=>setNewDoc({...newDoc,[field]:e.target.value})} style={inputStyle} placeholder={field==="id"?"MP-XX / QD-XXX":""} />\n',
'                </div>\n',
'              ))}\n',
'            </div>\n',
'            <div>\n',
'              <div style={{ fontSize:12, color:"#64748b", marginBottom:5 }}>\u6587\u4ef6\u540d\u7a31 *</div>\n',
'              <input type="text" value={newDoc.name} onChange={e=>setNewDoc({...newDoc,name:e.target.value})} style={inputStyle} />\n',
'            </div>\n',
'            <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 }}>\n',
'              <div>\n',
'                <div style={{ fontSize:12, color:"#64748b", marginBottom:5 }}>\u5236\u5b9a\u65e5\u671f *</div>\n',
'                <input type="date" value={newDoc.createdDate} onChange={e=>setNewDoc({...newDoc,createdDate:e.target.value})} style={inputStyle} />\n',
'              </div>\n',
'              <div>\n',
'                <div style={{ fontSize:12, color:"#64748b", marginBottom:5 }}>\u4fdd\u5b58\u5e74\u9650\uff08\u5e74\uff09</div>\n',
'                <input type="number" value={newDoc.retentionYears} onChange={e=>setNewDoc({...newDoc,retentionYears:e.target.value})} style={inputStyle} min="1" max="99" />\n',
'              </div>\n',
'            </div>\n',
'            <div>\n',
'              <div style={{ fontSize:12, color:"#64748b", marginBottom:5 }}>\u985e\u5225</div>\n',
'              <select value={newDoc.type} onChange={e=>setNewDoc({...newDoc,type:e.target.value})} style={inputStyle}>\n',
'                <option>\u7ba1\u7406\u624b\u518a</option><option>\u7ba1\u7406\u7a0b\u5e8f</option><option>\u4f5c\u696d\u6307\u5c0e\u66f8</option><option>\u8868\u55ae</option>\n',
'              </select>\n',
'            </div>\n',
'            {err && <div style={{ background:"rgba(239,68,68,0.1)", border:"1px solid rgba(239,68,68,0.3)", borderRadius:8, padding:"10px 14px", color:"#fca5a5", fontSize:13 }}>{err}</div>}\n',
'            <button onClick={handleAdd} style={{ background:"linear-gradient(135deg,#7c3aed,#4f46e5)", border:"none", borderRadius:10, color:"#fff", cursor:"pointer", padding:"13px 24px", fontSize:15, fontWeight:700, marginTop:4 }}>\uff0b \u78ba\u8a8d\u65b0\u589e\u6587\u4ef6</button>\n',
'          </div>\n',
'        </Modal>\n',
'      )}\n',
'    </div>\n',
'  );\n',
'}\n',
]

new_lines = lines[:START] + new_block + lines[END+1:]
print(f"New total lines: {len(new_lines)}")

with open(r'C:\Users\USER\Desktop\自動稽核程式\audit-dashboard.jsx', 'w', encoding='utf-8-sig') as f:
    f.writelines(new_lines)
print("Patch applied OK")
