lines = []

# ─── APP COMPONENT ────────────────────────────────────────────────────────────
lines.append('')
lines.append('// ─── MAIN APP ────────────────────────────────────────────────────────────────')
lines.append('export default function App() {')
lines.append('  const [activeTab, setActiveTab] = useState("home");')
lines.append('  const [instruments, setInstruments] = useState(initialInstruments);')
lines.append('  const [documents, setDocuments] = useState(initialDocuments);')
lines.append('  const [training, setTraining] = useState(initialTraining);')
lines.append('  const [equipment, setEquipment] = useState(initialEquipment);')
lines.append('  const [suppliers, setSuppliers] = useState(initialSuppliers);')
lines.append('  const [nonConformances, setNonConformances] = useState(initialNonConformances);')
lines.append('  const [auditPlans, setAuditPlans] = useState(initialAuditPlans);')
lines.append('  const [envRecords, setEnvRecords] = useState(initialEnvRecords);')
lines.append('')
lines.append('  const tabs = [')
lines.append('    { id: "home",           label: "\u4e3b\u63a7\u53f0",   icon: "\u2302" },')
lines.append('    { id: "calibration",    label: "\u6821\u6b63\u7ba1\u7406", icon: "\u25ce" },')
lines.append('    { id: "documents",      label: "\u6587\u4ef6\u7ba1\u7406", icon: "\u2261" },')
lines.append('    { id: "training",       label: "\u8a13\u7df4\u7ba1\u7406", icon: "\u25a1" },')
lines.append('    { id: "equipment",      label: "\u8a2d\u5099\u4fdd\u990a", icon: "\u2699" },')
lines.append('    { id: "supplier",       label: "\u4f9b\u61c9\u5546\u7ba1\u7406", icon: "\u25c8" },')
lines.append('    { id: "nonconformance", label: "\u4e0d\u7b26\u5408\u7ba1\u7406", icon: "\u26a0" },')
lines.append('    { id: "auditplan",      label: "\u7a3d\u6838\u8a08\u756b", icon: "\u2713" },')
lines.append('    { id: "environment",    label: "\u74b0\u5883\u76e3\u6e2c", icon: "\u25c9" },')
lines.append('    { id: "report",         label: "\u7a3d\u6838\u5831\u544a", icon: "\u2630" },')
lines.append('  ];')
lines.append('')
lines.append('  function renderTab() {')
lines.append('    switch(activeTab) {')
lines.append('      case "home":           return <DashboardHome instruments={instruments} documents={documents} training={training} equipment={equipment} suppliers={suppliers} nonConformances={nonConformances} auditPlans={auditPlans} envRecords={envRecords} setActiveTab={setActiveTab} />;')
lines.append('      case "calibration":    return <CalibrationTab instruments={instruments} setInstruments={setInstruments} />;')
lines.append('      case "documents":      return <DocumentsTab documents={documents} setDocuments={setDocuments} />;')
lines.append('      case "training":       return <TrainingTab training={training} setTraining={setTraining} />;')
lines.append('      case "equipment":      return <EquipmentTab equipment={equipment} setEquipment={setEquipment} />;')
lines.append('      case "supplier":       return <SupplierTab suppliers={suppliers} setSuppliers={setSuppliers} />;')
lines.append('      case "nonconformance": return <NonConformanceTab nonConformances={nonConformances} setNonConformances={setNonConformances} />;')
lines.append('      case "auditplan":      return <AuditPlanTab auditPlans={auditPlans} setAuditPlans={setAuditPlans} />;')
lines.append('      case "environment":    return <EnvironmentTab envRecords={envRecords} setEnvRecords={setEnvRecords} />;')
lines.append('      case "report":         return <ReportTab instruments={instruments} documents={documents} training={training} equipment={equipment} suppliers={suppliers} nonConformances={nonConformances} auditPlans={auditPlans} envRecords={envRecords} />;')
lines.append('      default:               return <DashboardHome instruments={instruments} documents={documents} training={training} equipment={equipment} suppliers={suppliers} nonConformances={nonConformances} auditPlans={auditPlans} envRecords={envRecords} setActiveTab={setActiveTab} />;')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  return (')
lines.append('    <div style={{ minHeight: "100vh", background: "linear-gradient(135deg, #0a0f1e 0%, #0d1117 50%, #080d1a 100%)", color: "#e2e8f0", fontFamily: "\'Noto Sans TC\', sans-serif" }}>')
lines.append('      <div style={{ background: "rgba(255,255,255,0.03)", borderBottom: "1px solid rgba(255,255,255,0.08)", padding: "0 24px" }}>')
lines.append('        <div style={{ display: "flex", alignItems: "center", gap: 0, overflowX: "auto" }}>')
lines.append('          {tabs.map(t => (')
lines.append('            <button key={t.id} onClick={() => setActiveTab(t.id)} style={{')
lines.append('              background: "none", border: "none", cursor: "pointer",')
lines.append('              padding: "16px 16px", fontSize: 12, fontWeight: 600,')
lines.append('              color: activeTab === t.id ? "#60a5fa" : "#64748b",')
lines.append('              borderBottom: activeTab === t.id ? "2px solid #60a5fa" : "2px solid transparent",')
lines.append('              whiteSpace: "nowrap", display: "flex", alignItems: "center", gap: 6,')
lines.append('              transition: "color 0.2s"')
lines.append('            }}>')
lines.append('              <span style={{ fontSize: 14 }}>{t.icon}</span>')
lines.append('              <span>{t.label}</span>')
lines.append('            </button>')
lines.append('          ))}')
lines.append('        </div>')
lines.append('      </div>')
lines.append('      <div style={{ maxWidth: 1400, margin: "0 auto", padding: "28px 24px" }}>')
lines.append('        {renderTab()}')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  );')
lines.append('}')

content = '\n'.join(lines) + '\n'
with open(r'C:\Users\USER\Desktop\自動稽核程式\audit-dashboard.jsx', 'a', encoding='utf-8-sig') as f:
    f.write(content)
print('Part10 App OK')
