lines = []
lines.append('')
lines.append('// ─── HELPERS ──────────────────────────────────────────────────────────────────')
lines.append('const today = new Date();')
lines.append('today.setHours(0, 0, 0, 0);')
lines.append('')
lines.append('function daysUntil(dateStr) {')
lines.append('  if (!dateStr) return 9999;')
lines.append('  const d = new Date(dateStr);')
lines.append('  d.setHours(0, 0, 0, 0);')
lines.append('  return Math.round((d - today) / 86400000);')
lines.append('}')
lines.append('')
lines.append('function addDays(dateStr, days) {')
lines.append('  const d = new Date(dateStr);')
lines.append('  d.setDate(d.getDate() + days);')
lines.append('  return d.toISOString().split("T")[0];')
lines.append('}')
lines.append('')
lines.append('function formatDate(dateStr) {')
lines.append('  if (!dateStr) return "\u2014";')
lines.append('  const d = new Date(dateStr);')
lines.append('  return `${d.getFullYear()}/${String(d.getMonth() + 1).padStart(2, "0")}/${String(d.getDate()).padStart(2, "0")}`;')
lines.append('}')
lines.append('')
lines.append('function urgencyColor(days) {')
lines.append('  if (days < 0) return "#ef4444";')
lines.append('  if (days <= 14) return "#f97316";')
lines.append('  if (days <= 30) return "#eab308";')
lines.append('  return "#22c55e";')
lines.append('}')
lines.append('')
lines.append('function urgencyLabel(days) {')
lines.append('  if (days === 9999) return "\u7121\u5230\u671f\u65e5";')
lines.append('  if (days < 0) return `\u903e\u671f ${Math.abs(days)} \u5929`;')
lines.append('  if (days === 0) return "\u4eca\u65e5\u5230\u671f";')
lines.append('  return `\u5269 ${days} \u5929`;')
lines.append('}')
lines.append('')
lines.append('function urgencyBg(days) {')
lines.append('  if (days < 0) return "rgba(239,68,68,0.12)";')
lines.append('  if (days <= 14) return "rgba(249,115,22,0.12)";')
lines.append('  if (days <= 30) return "rgba(234,179,8,0.12)";')
lines.append('  return "rgba(34,197,94,0.08)";')
lines.append('}')
lines.append('')
lines.append('// ─── SHARED COMPONENTS ────────────────────────────────────────────────────────')
lines.append('function Badge({ color, children }) {')
lines.append('  return (')
lines.append('    <span style={{')
lines.append('      display: "inline-block", padding: "2px 10px", borderRadius: 99,')
lines.append('      background: color + "22", color, fontSize: 12, fontWeight: 700,')
lines.append('      border: `1px solid ${color}44`, letterSpacing: 0.3,')
lines.append('    }}>{children}</span>')
lines.append('  );')
lines.append('}')
lines.append('')
lines.append('function StatCard({ label, value, color, sub }) {')
lines.append('  return (')
lines.append('    <div style={{')
lines.append('      background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.09)",')
lines.append('      borderRadius: 14, padding: "20px 24px", flex: 1, minWidth: 140,')
lines.append('      borderTop: `3px solid ${color}`,')
lines.append('    }}>')
lines.append('      <div style={{ fontSize: 32, fontWeight: 800, color, fontFamily: "\'DM Mono\', monospace", lineHeight: 1 }}>{value}</div>')
lines.append('      <div style={{ fontSize: 13, color: "#94a3b8", marginTop: 6, fontWeight: 600 }}>{label}</div>')
lines.append('      {sub && <div style={{ fontSize: 11, color: "#64748b", marginTop: 4 }}>{sub}</div>}')
lines.append('    </div>')
lines.append('  );')
lines.append('}')
lines.append('')
lines.append('function SectionHeader({ title, count, color = "#60a5fa" }) {')
lines.append('  return (')
lines.append('    <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}>')
lines.append('      <div style={{ width: 4, height: 22, background: color, borderRadius: 2 }} />')
lines.append('      <h2 style={{ margin: 0, fontSize: 17, fontWeight: 700, color: "#e2e8f0" }}>{title}</h2>')
lines.append('      {count !== undefined && (')
lines.append('        <span style={{ background: color + "22", color, borderRadius: 99, padding: "1px 10px", fontSize: 12, fontWeight: 700 }}>{count}</span>')
lines.append('      )}')
lines.append('    </div>')
lines.append('  );')
lines.append('}')
lines.append('')
lines.append('function Modal({ title, onClose, children }) {')
lines.append('  return (')
lines.append('    <div style={{')
lines.append('      position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", zIndex: 1000,')
lines.append('      display: "flex", alignItems: "center", justifyContent: "center", padding: 20,')
lines.append('    }} onClick={onClose}>')
lines.append('      <div style={{')
lines.append('        background: "#1e293b", borderRadius: 18, padding: 32, maxWidth: 700, width: "100%",')
lines.append('        maxHeight: "85vh", overflow: "auto", border: "1px solid rgba(255,255,255,0.1)",')
lines.append('        boxShadow: "0 32px 80px rgba(0,0,0,0.6)",')
lines.append('      }} onClick={e => e.stopPropagation()}>')
lines.append('        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>')
lines.append('          <h3 style={{ margin: 0, fontSize: 18, color: "#e2e8f0", fontWeight: 700 }}>{title}</h3>')
lines.append('          <button onClick={onClose} style={{')
lines.append('            background: "rgba(255,255,255,0.08)", border: "none", borderRadius: 8,')
lines.append('            color: "#94a3b8", cursor: "pointer", padding: "6px 14px", fontSize: 14,')
lines.append('          }}>\u2715 \u95dc\u9589</button>')
lines.append('        </div>')
lines.append('        {children}')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  );')
lines.append('}')
lines.append('')
lines.append('const inputStyle = {')
lines.append('  background: "rgba(255,255,255,0.07)", border: "1px solid rgba(255,255,255,0.15)",')
lines.append('  borderRadius: 8, padding: "8px 12px", color: "#e2e8f0", fontSize: 14, width: "100%", boxSizing: "border-box",')
lines.append('};')

content = '\n'.join(lines) + '\n'
with open(r'C:\Users\USER\Desktop\自動稽核程式\audit-dashboard.jsx', 'a', encoding='utf-8-sig') as f:
    f.write(content)
print('Part2 helpers OK')
