lines = []
# CalibrationTab
lines.append('')
lines.append('// ─── CALIBRATION TAB ─────────────────────────────────────────────────────────')
lines.append('function CalibrationTab({ instruments, setInstruments }) {')
lines.append('  const [modal, setModal] = useState(null);')
lines.append('  const [form, setForm] = useState({});')
lines.append('  const enriched = instruments.map(i => {')
lines.append('    const nextDate = i.status === "\u514d\u6821\u6b63" ? null : addDays(i.calibratedDate, i.intervalDays);')
lines.append('    const days = nextDate ? daysUntil(nextDate) : 9999;')
lines.append('    return { ...i, nextDate, days };')
lines.append('  }).sort((a, b) => a.days - b.days);')
lines.append('  function handleUpdate() {')
lines.append('    setInstruments(prev => prev.map(i => i.id === modal.id ? { ...i, calibratedDate: form.date, status: "\u5408\u683c" } : i));')
lines.append('    setModal(null);')
lines.append('  }')
lines.append('  return (')
lines.append('    <div>')
lines.append('      <SectionHeader title="\u91cf\u898f\u5100\u5668\u6821\u6b63\u8ffd\u8e64" count={enriched.length} color="#60a5fa" />')
lines.append('      <div style={{ display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" }}>')
lines.append('        <StatCard label="\u903e\u671f" value={enriched.filter(i => i.days < 0).length} color="#ef4444" />')
lines.append('        <StatCard label="14\u5929\u5167\u5230\u671f" value={enriched.filter(i => i.days >= 0 && i.days <= 14).length} color="#f97316" />')
lines.append('        <StatCard label="\u6b63\u5e38" value={enriched.filter(i => i.days > 30).length} color="#22c55e" />')
lines.append('        <StatCard label="\u514d\u6821\u6b63" value={enriched.filter(i => i.status === "\u514d\u6821\u6b63").length} color="#6366f1" />')
lines.append('      </div>')
lines.append('      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>')
lines.append('        {enriched.map(inst => inst.status === "\u514d\u6821\u6b63" ? (')
lines.append('          <div key={inst.id} style={{ background: "rgba(99,102,241,0.08)", border: "1px solid rgba(99,102,241,0.2)", borderRadius: 12, padding: "14px 18px", display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>')
lines.append('            <div style={{ flex: 1, minWidth: 200 }}>')
lines.append('              <div style={{ fontWeight: 700, color: "#c7d2fe", fontSize: 14 }}>{inst.name}</div>')
lines.append('              <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{inst.id} \u00b7 {inst.location}</div>')
lines.append('            </div>')
lines.append('            <Badge color="#6366f1">\u514d\u6821\u6b63</Badge>')
lines.append('          </div>')
lines.append('        ) : (')
lines.append('          <div key={inst.id} style={{ background: urgencyBg(inst.days), border: `1px solid ${urgencyColor(inst.days)}33`, borderRadius: 12, padding: "14px 18px", display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>')
lines.append('            <div style={{ flex: 1, minWidth: 200 }}>')
lines.append('              <div style={{ fontWeight: 700, color: "#e2e8f0", fontSize: 14 }}>{inst.name}</div>')
lines.append('              <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{inst.id} \u00b7 {inst.location} \u00b7 {inst.type}{inst.needsMSA && <span style={{ marginLeft: 8, color: "#818cf8", fontWeight: 700 }}>\u9700 MSA</span>}</div>')
lines.append('            </div>')
lines.append('            <div style={{ textAlign: "right", minWidth: 120 }}>')
lines.append('              <div style={{ fontSize: 12, color: "#64748b" }}>\u4e0b\u6b21\u6821\u6b63</div>')
lines.append('              <div style={{ fontWeight: 700, color: "#e2e8f0", fontSize: 14 }}>{formatDate(inst.nextDate)}</div>')
lines.append('            </div>')
lines.append('            <Badge color={urgencyColor(inst.days)}>{urgencyLabel(inst.days)}</Badge>')
lines.append('            <button onClick={() => { setModal(inst); setForm({ date: new Date().toISOString().split("T")[0] }); }} style={{ background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.15)", borderRadius: 8, color: "#94a3b8", cursor: "pointer", padding: "6px 14px", fontSize: 12, fontWeight: 600 }}>\u66f4\u65b0\u6821\u6b63</button>')
lines.append('          </div>')
lines.append('        ))}')
lines.append('      </div>')
lines.append('      {modal && (')
lines.append('        <Modal title={`\u66f4\u65b0\u6821\u6b63\u8a18\u9304\uff1a${modal.name}`} onClose={() => setModal(null)}>')
lines.append('          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>')
lines.append('            <div><div style={{ fontSize: 12, color: "#64748b", marginBottom: 6 }}>\u5100\u5668\u7de8\u865f</div><div style={{ color: "#e2e8f0", fontWeight: 600 }}>{modal.id}</div></div>')
lines.append('            <div><div style={{ fontSize: 12, color: "#64748b", marginBottom: 6 }}>\u672c\u6b21\u6821\u6b63\u65e5\u671f</div><input type="date" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} style={inputStyle} /></div>')
lines.append('            <div style={{ background: "rgba(34,197,94,0.1)", border: "1px solid rgba(34,197,94,0.2)", borderRadius: 8, padding: 12 }}>')
lines.append('              <div style={{ fontSize: 12, color: "#4ade80", fontWeight: 600 }}>\u66f4\u65b0\u5f8c\uff0c\u4e0b\u6b21\u6821\u6b63\u65e5\u671f\u5c07\u70ba\uff1a</div>')
lines.append('              <div style={{ color: "#86efac", fontWeight: 700, fontSize: 16, marginTop: 4 }}>{formatDate(addDays(form.date || modal.calibratedDate, modal.intervalDays))}</div>')
lines.append('            </div>')
lines.append('            <button onClick={handleUpdate} style={{ background: "linear-gradient(135deg, #3b82f6, #6366f1)", border: "none", borderRadius: 10, color: "#fff", cursor: "pointer", padding: "12px 24px", fontSize: 15, fontWeight: 700 }}>\u2713 \u78ba\u8a8d\u66f4\u65b0\u6821\u6b63\u8a18\u9304</button>')
lines.append('          </div>')
lines.append('        </Modal>')
lines.append('      )}')
lines.append('    </div>')
lines.append('  );')
lines.append('}')
lines.append('')
# DocumentsTab
lines.append('// ─── DOCUMENTS TAB ───────────────────────────────────────────────────────────')
lines.append('function DocumentsTab({ documents, setDocuments }) {')
lines.append('  const [modal, setModal] = useState(null);')
lines.append('  const [showAdd, setShowAdd] = useState(false);')
lines.append('  const [newDoc, setNewDoc] = useState({ id: "", name: "", type: "\u7ba1\u7406\u7a0b\u5e8f", version: "1.0", department: "", createdDate: "", author: "", retentionYears: 16 });')
lines.append('  const enriched = documents.map(d => {')
lines.append('    const expiryDate = new Date(d.createdDate);')
lines.append('    expiryDate.setFullYear(expiryDate.getFullYear() + d.retentionYears);')
lines.append('    const expiryStr = expiryDate.toISOString().split("T")[0];')
lines.append('    const daysToExpiry = daysUntil(expiryStr);')
lines.append('    return { ...d, expiryStr, daysToExpiry };')
lines.append('  });')
lines.append('  function handleAdd() {')
lines.append('    setDocuments(prev => [...prev, { ...newDoc, retentionYears: parseInt(newDoc.retentionYears) }]);')
lines.append('    setShowAdd(false);')
lines.append('    setNewDoc({ id: "", name: "", type: "\u7ba1\u7406\u7a0b\u5e8f", version: "1.0", department: "", createdDate: "", author: "", retentionYears: 16 });')
lines.append('  }')
lines.append('  return (')
lines.append('    <div>')
lines.append('      <SectionHeader title="\u6587\u4ef6\u7248\u672c\u7ba1\u63a7" count={documents.length} color="#a78bfa" />')
lines.append('      <div style={{ display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" }}>')
lines.append('        <StatCard label="\u7ba1\u7406\u624b\u518a" value={documents.filter(d => d.type === "\u7ba1\u7406\u624b\u518a").length} color="#a78bfa" />')
lines.append('        <StatCard label="\u7ba1\u7406\u7a0b\u5e8f" value={documents.filter(d => d.type === "\u7ba1\u7406\u7a0b\u5e8f").length} color="#60a5fa" />')
lines.append('        <StatCard label="\u7e3d\u6587\u4ef6\u6578" value={documents.length} color="#34d399" />')
lines.append('      </div>')
lines.append('      <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 14 }}>')
lines.append('        <button onClick={() => setShowAdd(true)} style={{ background: "linear-gradient(135deg, #7c3aed, #4f46e5)", border: "none", borderRadius: 10, color: "#fff", cursor: "pointer", padding: "9px 18px", fontSize: 13, fontWeight: 700 }}>\uff0b \u65b0\u589e\u6587\u4ef6</button>')
lines.append('      </div>')
lines.append('      <div style={{ overflowX: "auto" }}>')
lines.append('        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>')
lines.append('          <thead><tr>{["\u6587\u4ef6\u7de8\u865f","\u6587\u4ef6\u540d\u7a31","\u985e\u5225","\u7248\u672c","\u5236\u5b9a\u90e8\u9580","\u5236\u5b9a\u65e5\u671f","\u5236\u5b9a\u8005","\u4fdd\u5b58\u81f3",""].map(h => (<th key={h} style={{ textAlign: "left", padding: "10px 12px", color: "#64748b", fontWeight: 600, borderBottom: "1px solid rgba(255,255,255,0.06)", whiteSpace: "nowrap" }}>{h}</th>))}</tr></thead>')
lines.append('          <tbody>')
lines.append('            {enriched.map((doc, i) => (')
lines.append('              <tr key={doc.id} style={{ background: i % 2 === 0 ? "rgba(255,255,255,0.02)" : "transparent" }}>')
lines.append('                <td style={{ padding: "10px 12px", color: "#60a5fa", fontWeight: 700, fontFamily: "monospace" }}>{doc.id}</td>')
lines.append('                <td style={{ padding: "10px 12px", color: "#e2e8f0", fontWeight: 600 }}>{doc.name}</td>')
lines.append('                <td style={{ padding: "10px 12px" }}><Badge color={doc.type === "\u7ba1\u7406\u624b\u518a" ? "#a78bfa" : "#60a5fa"}>{doc.type}</Badge></td>')
lines.append('                <td style={{ padding: "10px 12px" }}><span style={{ background: "rgba(34,197,94,0.1)", color: "#4ade80", borderRadius: 6, padding: "2px 8px", fontWeight: 700, fontFamily: "monospace" }}>v{doc.version}</span></td>')
lines.append('                <td style={{ padding: "10px 12px", color: "#94a3b8" }}>{doc.department}</td>')
lines.append('                <td style={{ padding: "10px 12px", color: "#94a3b8", whiteSpace: "nowrap" }}>{formatDate(doc.createdDate)}</td>')
lines.append('                <td style={{ padding: "10px 12px", color: "#94a3b8" }}>{doc.author}</td>')
lines.append('                <td style={{ padding: "10px 12px", whiteSpace: "nowrap" }}><span style={{ color: doc.daysToExpiry < 365 ? "#f97316" : "#64748b", fontFamily: "monospace", fontSize: 12 }}>{formatDate(doc.expiryStr)}</span></td>')
lines.append('                <td style={{ padding: "10px 12px" }}><button onClick={() => setModal(doc)} style={{ background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 6, color: "#94a3b8", cursor: "pointer", padding: "4px 10px", fontSize: 11 }}>\u8a73\u60c5</button></td>')
lines.append('              </tr>')
lines.append('            ))}')
lines.append('          </tbody>')
lines.append('        </table>')
lines.append('      </div>')
lines.append('      {modal && (<Modal title={`\u6587\u4ef6\u8a73\u60c5\uff1a${modal.id}`} onClose={() => setModal(null)}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>{[["\u6587\u4ef6\u7de8\u865f", modal.id],["\u6587\u4ef6\u540d\u7a31", modal.name],["\u985e\u5225", modal.type],["\u7248\u672c", `v${modal.version}`],["\u5236\u5b9a\u90e8\u9580", modal.department],["\u5236\u5b9a\u65e5\u671f", formatDate(modal.createdDate)],["\u5236\u5b9a\u8005", modal.author],["\u4fdd\u5b58\u5e74\u9650", `${modal.retentionYears} \u5e74`],["\u4fdd\u5b58\u5230\u671f\u65e5", formatDate(modal.expiryStr)],["\u8ddd\u5230\u671f", `${modal.daysToExpiry} \u5929`]].map(([k,v]) => (<div key={k}><div style={{ fontSize: 11, color: "#64748b", marginBottom: 4 }}>{k}</div><div style={{ color: "#e2e8f0", fontWeight: 600, fontSize: 14 }}>{v}</div></div>))}</div></Modal>)}')
lines.append('      {showAdd && (<Modal title="\u65b0\u589e\u6587\u4ef6" onClose={() => setShowAdd(false)}><div style={{ display: "flex", flexDirection: "column", gap: 12 }}>{[["\u6587\u4ef6\u7de8\u865f","id","text"],["\u6587\u4ef6\u540d\u7a31","name","text"],["\u5236\u5b9a\u90e8\u9580","department","text"],["\u5236\u5b9a\u65e5\u671f","createdDate","date"],["\u5236\u5b9a\u8005","author","text"],["\u7248\u672c","version","text"],["\u4fdd\u5b58\u5e74\u9650(\u5e74)","retentionYears","number"]].map(([label,field,type]) => (<div key={field}><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>{label}</div><input type={type} value={newDoc[field]} onChange={e => setNewDoc({ ...newDoc, [field]: e.target.value })} style={inputStyle} /></div>))}<div><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>\u985e\u5225</div><select value={newDoc.type} onChange={e => setNewDoc({ ...newDoc, type: e.target.value })} style={inputStyle}><option>\u7ba1\u7406\u624b\u518a</option><option>\u7ba1\u7406\u7a0b\u5e8f</option><option>\u4f5c\u696d\u6307\u5c0e\u66f8</option><option>\u8868\u55ae</option></select></div><button onClick={handleAdd} style={{ background: "linear-gradient(135deg, #7c3aed, #4f46e5)", border: "none", borderRadius: 10, color: "#fff", cursor: "pointer", padding: "12px 24px", fontSize: 15, fontWeight: 700, marginTop: 8 }}>\uff0b \u65b0\u589e\u6587\u4ef6</button></div></Modal>)}')
lines.append('    </div>')
lines.append('  );')
lines.append('}')

content = '\n'.join(lines) + '\n'
with open(r'C:\Users\USER\Desktop\自動稽核程式\audit-dashboard.jsx', 'a', encoding='utf-8-sig') as f:
    f.write(content)
print('Part3 CalibrationTab+DocumentsTab OK')
