lines = []
# TrainingTab
lines.append('')
lines.append('// ─── TRAINING TAB ─────────────────────────────────────────────────────────────')
lines.append('function TrainingTab({ training, setTraining }) {')
lines.append('  const [selected, setSelected] = useState(null);')
lines.append('  const [showAdd, setShowAdd] = useState(false);')
lines.append('  const [newRecord, setNewRecord] = useState({ course: "", date: "", type: "\u5167\u8a13", result: "\u5408\u683c", cert: "\u7121" });')
lines.append('  function addTraining() {')
lines.append('    setTraining(prev => prev.map(emp => emp.id === selected.id ? { ...emp, trainings: [...emp.trainings, { ...newRecord }] } : emp));')
lines.append('    setSelected(prev => ({ ...prev, trainings: [...prev.trainings, { ...newRecord }] }));')
lines.append('    setShowAdd(false);')
lines.append('    setNewRecord({ course: "", date: "", type: "\u5167\u8a13", result: "\u5408\u683c", cert: "\u7121" });')
lines.append('  }')
lines.append('  return (')
lines.append('    <div>')
lines.append('      <SectionHeader title="\u4eba\u54e1\u8a13\u7df4\u8a18\u9304" count={training.length} color="#34d399" />')
lines.append('      <div style={{ display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" }}>')
lines.append('        <StatCard label="\u54e1\u5de5\u4eba\u6578" value={training.length} color="#34d399" />')
lines.append('        <StatCard label="\u8a13\u7df4\u7e3d\u7b46\u6578" value={training.reduce((s,e) => s+e.trainings.length,0)} color="#60a5fa" />')
lines.append('        <StatCard label="\u5916\u8a13\u7b46\u6578" value={training.reduce((s,e) => s+e.trainings.filter(t=>t.type==="\u5916\u8a13").length,0)} color="#a78bfa" />')
lines.append('        <StatCard label="\u6709\u8b49\u66f8\u7b46\u6578" value={training.reduce((s,e) => s+e.trainings.filter(t=>t.cert==="\u6709").length,0)} color="#f472b6" />')
lines.append('      </div>')
lines.append('      <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>')
lines.append('        <div style={{ flex: "0 0 260px", display: "flex", flexDirection: "column", gap: 8 }}>')
lines.append('          {training.map(emp => {')
lines.append('            const hireMonths = Math.floor((today - new Date(emp.hireDate)) / (30*86400000));')
lines.append('            const isNew = hireMonths < 3;')
lines.append('            return (<div key={emp.id} onClick={() => setSelected(emp)} style={{ background: selected?.id===emp.id?"rgba(52,211,153,0.15)":"rgba(255,255,255,0.04)", border: `1px solid ${selected?.id===emp.id?"rgba(52,211,153,0.4)":"rgba(255,255,255,0.08)"}`, borderRadius: 12, padding: "14px 16px", cursor: "pointer" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><div style={{ fontWeight: 700, color: "#e2e8f0", fontSize: 14 }}>{emp.name}</div><div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{emp.dept} \u00b7 {emp.role}</div></div><div style={{ textAlign: "right" }}>{isNew&&<Badge color="#f97316">\u65b0\u9032</Badge>}<div style={{ fontSize: 11, color: "#64748b", marginTop: 4 }}>{emp.trainings.length} \u7b46\u8a13\u7df4</div></div></div></div>);')
lines.append('          })}')
lines.append('        </div>')
lines.append('        <div style={{ flex: 1, minWidth: 280 }}>')
lines.append('          {selected ? (')
lines.append('            <div>')
lines.append('              <div style={{ background: "rgba(255,255,255,0.04)", borderRadius: 12, padding: 16, border: "1px solid rgba(255,255,255,0.08)", marginBottom: 14 }}>')
lines.append('                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>')
lines.append('                  <div>')
lines.append('                    <div style={{ fontSize: 18, fontWeight: 800, color: "#e2e8f0" }}>{selected.name}</div>')
lines.append('                    <div style={{ color: "#64748b", fontSize: 13, marginTop: 4 }}>{selected.id} \u00b7 {selected.dept} \u00b7 {selected.role}</div>')
lines.append('                    <div style={{ color: "#64748b", fontSize: 12, marginTop: 2 }}>\u5230\u8077\u65e5\uff1a{formatDate(selected.hireDate)}</div>')
lines.append('                  </div>')
lines.append('                  <button onClick={() => setShowAdd(true)} style={{ background: "linear-gradient(135deg, #059669, #10b981)", border: "none", borderRadius: 8, color: "#fff", cursor: "pointer", padding: "7px 14px", fontSize: 12, fontWeight: 700 }}>\uff0b \u65b0\u589e\u8a13\u7df4</button>')
lines.append('                </div>')
lines.append('              </div>')
lines.append('              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>')
lines.append('                {selected.trainings.map((t,i) => (<div key={i} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 10, padding: "12px 16px", display: "flex", gap: 16, alignItems: "center" }}><div style={{ flex: 1 }}><div style={{ fontWeight: 600, color: "#e2e8f0", fontSize: 13 }}>{t.course}</div><div style={{ fontSize: 11, color: "#64748b", marginTop: 3 }}>{formatDate(t.date)} \u00b7 {t.type}</div></div><Badge color={t.result==="\u5408\u683c"?"#22c55e":"#ef4444"}>{t.result}</Badge>{t.cert==="\u6709"&&<Badge color="#a78bfa">\u6709\u8b49\u66f8</Badge>}</div>))}')
lines.append('              </div>')
lines.append('            </div>')
lines.append('          ) : (<div style={{ textAlign: "center", padding: "60px 20px", color: "#475569" }}>\u2190 \u9ede\u9078\u5de6\u5074\u54e1\u5de5\u4ee5\u67e5\u770b\u8a13\u7df4\u8a18\u9304</div>)}')
lines.append('        </div>')
lines.append('      </div>')
lines.append('      {showAdd && selected && (<Modal title={`\u65b0\u589e\u8a13\u7df4\u8a18\u9304\uff1a${selected.name}`} onClose={() => setShowAdd(false)}><div style={{ display: "flex", flexDirection: "column", gap: 12 }}><div><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>\u8ab2\u7a0b\u540d\u7a31</div><input value={newRecord.course} onChange={e => setNewRecord({...newRecord,course:e.target.value})} style={inputStyle} /></div><div><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>\u8a13\u7df4\u65e5\u671f</div><input type="date" value={newRecord.date} onChange={e => setNewRecord({...newRecord,date:e.target.value})} style={inputStyle} /></div><div><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>\u8a13\u7df4\u985e\u578b</div><select value={newRecord.type} onChange={e => setNewRecord({...newRecord,type:e.target.value})} style={inputStyle}><option>\u5167\u8a13</option><option>\u5916\u8a13</option></select></div><div><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>\u8a55\u4f30\u7d50\u679c</div><select value={newRecord.result} onChange={e => setNewRecord({...newRecord,result:e.target.value})} style={inputStyle}><option>\u5408\u683c</option><option>\u4e0d\u5408\u683c</option><option>\u5f85\u8a55\u4f30</option></select></div><div><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>\u662f\u5426\u6709\u7d50\u696d\u8b49\u66f8</div><select value={newRecord.cert} onChange={e => setNewRecord({...newRecord,cert:e.target.value})} style={inputStyle}><option>\u7121</option><option>\u6709</option></select></div><button onClick={addTraining} style={{ background: "linear-gradient(135deg, #059669, #10b981)", border: "none", borderRadius: 10, color: "#fff", cursor: "pointer", padding: "12px 24px", fontSize: 15, fontWeight: 700, marginTop: 8 }}>\u2713 \u5132\u5b58\u8a13\u7df4\u8a18\u9304</button></div></Modal>)}')
lines.append('    </div>')
lines.append('  );')
lines.append('}')
lines.append('')
# EquipmentTab
lines.append('// ─── EQUIPMENT TAB ────────────────────────────────────────────────────────────')
lines.append('function EquipmentTab({ equipment, setEquipment }) {')
lines.append('  const [modal, setModal] = useState(null);')
lines.append('  const [form, setForm] = useState({});')
lines.append('  const enriched = equipment.map(eq => {')
lines.append('    const nextDate = addDays(eq.lastMaintenance, eq.intervalDays);')
lines.append('    const days = daysUntil(nextDate);')
lines.append('    return { ...eq, nextDate, days };')
lines.append('  }).sort((a,b) => a.days-b.days);')
lines.append('  function handleUpdate() {')
lines.append('    setEquipment(prev => prev.map(e => e.id===modal.id ? { ...e, lastMaintenance: form.date } : e));')
lines.append('    setModal(null);')
lines.append('  }')
lines.append('  return (')
lines.append('    <div>')
lines.append('      <SectionHeader title="\u8a2d\u5099\u4fdd\u990a\u8ffd\u8e64" count={equipment.length} color="#fb923c" />')
lines.append('      <div style={{ display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" }}>')
lines.append('        <StatCard label="\u903e\u671f\u4fdd\u990a" value={enriched.filter(e=>e.days<0).length} color="#ef4444" />')
lines.append('        <StatCard label="\u672c\u6708\u5230\u671f" value={enriched.filter(e=>e.days>=0&&e.days<=30).length} color="#f97316" />')
lines.append('        <StatCard label="\u6b63\u5e38" value={enriched.filter(e=>e.days>30).length} color="#22c55e" />')
lines.append('      </div>')
lines.append('      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>')
lines.append('        {enriched.map(eq => (')
lines.append('          <div key={eq.id} style={{ background: urgencyBg(eq.days), border: `1px solid ${urgencyColor(eq.days)}33`, borderRadius: 12, padding: "16px 18px" }}>')
lines.append('            <div style={{ display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap", marginBottom: 10 }}>')
lines.append('              <div style={{ flex: 1, minWidth: 200 }}><div style={{ fontWeight: 700, color: "#e2e8f0", fontSize: 14 }}>{eq.name}</div><div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{eq.id} \u00b7 {eq.location} \u00b7 \u6bcf {eq.intervalDays} \u5929\u4fdd\u990a\u4e00\u6b21</div></div>')
lines.append('              <div style={{ textAlign: "right", minWidth: 120 }}><div style={{ fontSize: 12, color: "#64748b" }}>\u4e0b\u6b21\u4fdd\u990a</div><div style={{ fontWeight: 700, color: "#e2e8f0" }}>{formatDate(eq.nextDate)}</div></div>')
lines.append('              <Badge color={urgencyColor(eq.days)}>{urgencyLabel(eq.days)}</Badge>')
lines.append('              <button onClick={() => { setModal(eq); setForm({ date: new Date().toISOString().split("T")[0] }); }} style={{ background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.15)", borderRadius: 8, color: "#94a3b8", cursor: "pointer", padding: "6px 14px", fontSize: 12 }}>\u8a18\u9304\u4fdd\u990a</button>')
lines.append('            </div>')
lines.append('            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>')
lines.append('              <span style={{ fontSize: 11, color: "#64748b", fontWeight: 600 }}>\u4fdd\u990a\u9805\u76ee\uff1a</span>')
lines.append('              {eq.nextItems.map((item,i) => (<span key={i} style={{ fontSize: 11, background: "rgba(251,146,60,0.1)", color: "#fb923c", borderRadius: 6, padding: "2px 8px", border: "1px solid rgba(251,146,60,0.2)" }}>{item}</span>))}')
lines.append('            </div>')
lines.append('          </div>')
lines.append('        ))}')
lines.append('      </div>')
lines.append('      {modal && (<Modal title={`\u8a18\u9304\u4fdd\u990a\u5b8c\u6210\uff1a${modal.name}`} onClose={() => setModal(null)}><div style={{ display: "flex", flexDirection: "column", gap: 16 }}><div><div style={{ fontSize: 12, color: "#64748b", marginBottom: 6 }}>\u4fdd\u990a\u5b8c\u6210\u65e5\u671f</div><input type="date" value={form.date} onChange={e => setForm({...form,date:e.target.value})} style={inputStyle} /></div><div style={{ background: "rgba(251,146,60,0.1)", borderRadius: 8, padding: 12 }}><div style={{ fontSize: 12, color: "#fb923c", fontWeight: 600, marginBottom: 8 }}>\u672c\u6b21\u4fdd\u990a\u9805\u76ee\uff1a</div>{modal.nextItems.map((item,i) => (<div key={i} style={{ color: "#fed7aa", fontSize: 13, marginBottom: 4 }}>\u2611 {item}</div>))}</div><button onClick={handleUpdate} style={{ background: "linear-gradient(135deg, #ea580c, #f97316)", border: "none", borderRadius: 10, color: "#fff", cursor: "pointer", padding: "12px 24px", fontSize: 15, fontWeight: 700 }}>\u2713 \u78ba\u8a8d\u4fdd\u990a\u5b8c\u6210</button></div></Modal>)}')
lines.append('    </div>')
lines.append('  );')
lines.append('}')

content = '\n'.join(lines) + '\n'
with open(r'C:\Users\USER\Desktop\自動稽核程式\audit-dashboard.jsx', 'a', encoding='utf-8-sig') as f:
    f.write(content)
print('Part4 TrainingTab+EquipmentTab OK')
