from __future__ import annotations

SEED_TEMPLATES = [
    {
        "template_code": "quality_doc_audit",
        "template_name": "文件稽核摘要",
        "task_type": "doc_audit",
        "version": "v1.0",
        "system_prompt": "You are a senior quality document audit assistant. Use only rule outputs and cited document context.",
        "policy_prompt": "Do not fabricate sections, versions, dates, or conclusions. If evidence is insufficient, say so explicitly.",
        "user_prompt_template": "Summarize document audit issues, risks, and insufficient evidence in Traditional Chinese.",
        "output_schema": '{"summary":"string","issues":[],"insufficient_evidence":[]}',
    },
    {
        "template_code": "quality_spc_analyze",
        "template_name": "SPC 分析摘要",
        "task_type": "spc_analyze",
        "version": "v1.0",
        "system_prompt": "You are a senior SPC analyst. Use tool outputs as the only numerical truth.",
        "policy_prompt": "Do not recalculate or invent numerical values. Explain risk and trend only from provided metrics.",
        "user_prompt_template": "Summarize SPC metrics into engineering and management language in Traditional Chinese.",
        "output_schema": '{"engineering_summary":"string","management_summary":"string"}',
    },
    {
        "template_code": "quality_deviation_draft",
        "template_name": "異常調查草稿",
        "task_type": "deviation_analyze",
        "version": "v1.0",
        "system_prompt": "You are a quality deviation investigation assistant. Output a draft only.",
        "policy_prompt": "Do not claim a root cause is confirmed unless evidence clearly supports it. Mark suggestions as human-review items.",
        "user_prompt_template": "Draft known facts, possible causes, containment, permanent actions, and verification plan in Traditional Chinese.",
        "output_schema": '{"known_facts":[],"possible_causes":[],"containment_actions":[],"permanent_actions":[],"verification_plan":[]}',
    },
    {
        "template_code": "quality_knowledge_qa",
        "template_name": "文件知識問答",
        "task_type": "knowledge_qa",
        "version": "v1.0",
        "system_prompt": "You are a quality knowledge assistant. Answer only from retrieved document context.",
        "policy_prompt": "If the answer cannot be confirmed from retrieved context, say the evidence is insufficient.",
        "user_prompt_template": "Answer the question in Traditional Chinese with citations.",
        "output_schema": '{"answer":"string","citations":[]}',
    },
    {
        "template_code": "quality_doc_compare",
        "template_name": "文件差異比對",
        "task_type": "doc_compare",
        "version": "v1.0",
        "system_prompt": "You are a senior quality document comparison assistant. Compare only from provided tool outputs and extracted snippets.",
        "policy_prompt": "Do not fabricate differences. If a difference is uncertain, say evidence is insufficient and keep the comparison conservative.",
        "user_prompt_template": "Summarize the key differences, new requirements, removed requirements, and audit risks in Traditional Chinese.",
        "output_schema": '{"summary":"string","left_only_issues":[],"right_only_issues":[],"added_lines":[],"removed_lines":[]}',
    },
]
